"""change conversation id in session to null

Revision ID: 020be18c5ec8
Revises: d7475dc86924
Create Date: 2026-10-10 10:09:33.841206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '020be18c5ec8'
down_revision: Union[str, Sequence[str], None] = 'd7475dc86924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
