"""create llm response table

Revision ID: 499babc5abc4
Revises: f8f3b4aae951
Create Date: 2026-07-10 19:22:33.206059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '499babc5abc4'
down_revision: Union[str, Sequence[str], None] = 'f8f3b4aae951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_response',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('llm_response', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('attachments', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('message', 'attachments')
    op.drop_column('message', 'content_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('content_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('message', sa.Column('attachments', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_table('llm_response')
    # ### end Alembic commands ###
