"""update conversation table

Revision ID: d7475dc86924
Revises: dbbd6feebdc0
Create Date: 2026-10-09 17:01:29.441517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7475dc86924'
down_revision: Union[str, Sequence[str], None] = 'dbbd6feebdc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('session_id', sa.UUID(), nullable=False))
    op.add_column('conversation', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'title')
    op.drop_column('conversation', 'session_id')
    # ### end Alembic commands ###
