"""rename column

Revision ID: dbbd6feebdc0
Revises: 78be4d297ee2
Create Date: 2026-10-07 19:22:14.276536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbbd6feebdc0'
down_revision: Union[str, Sequence[str], None] = '78be4d297ee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('conversation_id', sa.UUID(), nullable=False))
    op.drop_column('session', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('session', 'conversation_id')
    # ### end Alembic commands ###
