"""delete test table

Revision ID: 3916e65e7e95
Revises: fe4c762525bf
Create Date: 2026-07-08 09:53:29.759330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3916e65e7e95'
down_revision: Union[str, Sequence[str], None] = 'fe4c762525bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_name_business_sector'), table_name='company_name')
    op.drop_index(op.f('ix_company_name_company_name'), table_name='company_name')
    op.drop_index(op.f('ix_company_name_stock_id'), table_name='company_name')
    op.drop_table('company_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_name',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('stock_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('capitalization', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('business_sector', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('company_name_pkey'))
    )
    op.create_index(op.f('ix_company_name_stock_id'), 'company_name', ['stock_id'], unique=False)
    op.create_index(op.f('ix_company_name_company_name'), 'company_name', ['company_name'], unique=False)
    op.create_index(op.f('ix_company_name_business_sector'), 'company_name', ['business_sector'], unique=False)
    # ### end Alembic commands ###
